---
sudo: false
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  fast_finish: true
  allow_failures: 'Puppet 4.10'
  include:
    - rvm: 2.1.9
      name: 'Puppet 4.10'
      env: PUPPET_GEM_VERSION="~> 4.10" FACTER_GEM_VERSION="~> 2.0"
    - rvm: 2.4.4
      name: 'Puppet 5.0'
      env: PUPPET_GEM_VERSION="~> 5.0" FACTER_GEM_VERSION="> 2.0.1"
    - rvm: 2.4.4
      name: 'Puppet 5.5'
      env: PUPPET_GEM_VERSION="~> 5.5" FACTER_GEM_VERSION="> 2.0.1"
    - rvm: 2.4.4
      name: 'Puppet 6'
      env: PUPPET_GEM_VERSION="~> 6.0" FACTER_GEM_VERSION="> 2.0.1"
notifications:
  email: false
